version: "3.4"
services:
  db:
    image: mysql:5.7.22
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: sales
    ports:
      - "3308:3306"
    networks:
      - sales-network    
  salesmanegement:
    image: salesmanegement
    restart: always
    build:
      context:  .
      dockerfile: Dockerfile
    working_dir: /
    environment:
      TZ: America/Sao_Paulo
    ports:
      - "8080:8080"
    command: mvn spring-boot:run
    links:
      - db
    depends_on:
      - db
    networks:
      - sales-network   
networks:
    sales-network:
        driver: bridge
